name: CI

on:
  push:
      
jobs:
  qa:
    name: QA
    uses: ./.github/workflows/cqa.yml
    secrets: inherit

  manual_trigger:
    name: Trigger manual
    runs-on: ubuntu-latest
    environment: Develop-manual
    steps:
      run: echo "Yess"
